# Generated by Django 4.1.3 on 2022-11-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('slug', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('parent_slug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rates.region')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('dest_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_ports', to='rates.port')),
                ('orig_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_ports', to='rates.port')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='parent_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.region'),
        ),
    ]
