# Generated by Django 4.1.3 on 2022-11-13 09:24

import os
import ijson

from django.db import migrations
from django.conf import settings


def dump_data_into_model(model_name, json_file_name):
    """Read data from the json file and dump data into the specified model/table"""

    with open(os.path.join(settings.BASE_DIR, json_file_name), "r") as file:
        # ijson module will read json files efficiently
        data = (model_name(**obj) for obj in ijson.items(file, "item"))
        model_name.objects.bulk_create(data)


def dump_data_into_database(apps, schema_editor):
    """Dump data of regions, ports and prices"""

    # dump regions data
    dump_data_into_model(apps.get_model("rates", "region"), "regions.json")

    # dump ports data
    dump_data_into_model(apps.get_model("rates", "port"), "ports.json")

    # dump prices data
    dump_data_into_model(apps.get_model("rates", "price"), "prices.json")


def revert_database_dump(apps, schema_editor):
    """Revert database dump action. i.e Delete all the data from regions, ports and prices"""

    apps.get_model("rates", "region").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0002_alter_region_parent_slug"),
    ]

    operations = [
        migrations.RunPython(dump_data_into_database, revert_database_dump),
    ]
